### PR TITLE
Add 'private_file' option to MicrobTranscriptomicsRawSeqSet node

### PR DESCRIPTION
**Pull request by cometsong**

### CODE REVIEW

**Comment by cometsong** [comment]
@victor73 
As there are no conflicts, shall I just go ahead and merge the pull request?  Or would you like to also add a version tag update for next release?

**Comment by cometsong** [comment]
As there are no conflicts, shall I just go ahead and merge the pull request?  Or would you like to also add a version tag update for next release?

**Comment by victor73** [comment]
Hold off on that for a bit. It seems there is a set of uncommitted changes somewhere that I have to track down.

**Comment by cometsong** [comment]
As a side note, I'm now using the modified cutlass node modules to submit our data, as those allow me to submit nodes without local_file, and with my pseudo-hack of md5 = 32 0's and size=0.

**Comment by cometsong** [comment]
Your latest release/tag has come through, but this node (plus the tow 16S nodes) are still not privatizable. 
FYI.

**Comment by victor73** [comment]
Yup, I'm aware. That's why I haven't closed the 2 PRs yet. Located one set of commits but not the other (yet).

**Comment by cometsong** [comment]
Ok i'll leave it in your hands, as i'm using my mod'd versions to do the actual submits anyway.  

All you, All good.  :)

**Comment by victor73** [comment]
Looks like the changes from this PR are largely the same as other commits from August. For whatever reason, the changes are flagged as conflicts. This may be because the changes are so close to each other. Closing, but all credit to @cometsong for having found the problem in the first place.

**Pull request closed without merging**
