### PR TITLE
Addded all the test cases, still trouble with the SeqSet and TrimmedS…

### PR DESCRIPTION
**Pull request by abhishek9691**
Added all the test cases, made a couple changes to the classes themselves. I am still having trouble with the 16s and WGS Sequence Sets and the 16s Trimmed Sequence Set. I am unable to save without some file for a specific study in a remote location. I provide a local file, but the remote file must also exist apparently (remote_path in the respective class files). I also added a 'test_all' script that runs through and executes all the tests at once.

### CODE REVIEW

**Comment by abhishek9691** [comment]
Added the PyDoc strings to each class, and removed my login credentials to the OSDF system

**Comment by victor73** [comment]
Abhishek,

Some notes:
- See if you can give me two pull requests. One for the tests and one for the pydoc.
- The classes are showing up as conflicts for me because you're using windows style newlines instead of Unix. Therefore, all lines appear to be modified. Recommend you alter your text editor settings to use Unix style newlines or run the files through dos2unix or similar before committing...
- Try to limit the pydoc comments to no more than 80 to 90 columns.

-Victor

**Comment by abhishek9691** [comment]
Corrected all the PyDoc lengths and the issue with the line endings being DOS, changed to UNIX now.

**Comment by abhishek9691** [comment]
Added unit tests, corrected the line ending issue (hopefully), and added a new line (just random blank line) to each file so that it would push to my repository.

**Pull request closed without merging**
